export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const PLACE_FAILURE = "PLACE_FAILURE";
export const FETCH_PLACE_BY_ID_SUCCESS = "FETCH_PLACE_BY_ID_SUCCESS";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";

export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";

export const PHOTOS_FAILURE = "PHOTOS_FAILURE";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";

export const DELETE_ERRORS = "DELETE_ERRORS";