export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";
export const FETCH_ITEM_BY_ID_FAILURE = "FETCH_ITEM_BY_ID_FAILURE";
export const FETCH_ITEM_BY_ID_SUCCESS = "FETCH_ITEM_BY_ID_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";