export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const ADD_PLACE_FAILURE = "ADD_PLACE_FAILURE";
export const FETCH_PLACE_BY_ID_FAILURE = "FETCH_PLACE_BY_ID_FAILURE";
export const FETCH_PLACE_BY_ID_SUCCESS = "FETCH_PLACE_BY_ID_SUCCESS";
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";

export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const ADD_PHOTO_FAILURE = "ADD_PHOTO_FAILURE";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE";